name: Auto SSL

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'test'
        default: 'latest'
        required: false
        type: string

env:
  ACME: /home/runner/.acme.sh/acme.sh
  Ali_Key: ${{ secrets.Ali_Key }}
  Ali_Secret: ${{ secrets.Ali_Secret }}

jobs:
  acme:
    runs-on: ubuntu-latest
    steps:
      - name: Install ACME.SH
        run: |
          curl  https://get.acme.sh | sh
      - uses: actions/checkout@v3
      - name: Create xuexb SSL
        run: |
          mkdir -p ./ca/apijs.net
          $ACME --issue \
            --server letsencrypt \
            --dns dns_ali \
            --log \
            -d "apijs.net" \
            -d "*.apijs.net"
          $ACME --installcert \
            -d "apijs.net" \
            --key-file ./ca/apijs.net/apijs.net.key \
            --fullchain-file ./ca/apijs.net/apijs.net.cer
      - name: Git push
        run: |
          git config user.name xuexb
          git config user.email fe.xiaowu@gmail.com
          git add .
          git commit -m "feat: Add SSL [skip ci]"
          git push
