name: Deploy

on:
  workflow_call:
    inputs:
      envname:
        description: '部署环境'
        default: 'dev'
        type: string
      version:
        description: '部署版本'
        default: 'master'
        type: string

env:
  IMAGE_VERSION: ${{ inputs.version || github.event.inputs.version }}

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        run: |
          echo ${{ env.IMAGE_VERSION }}
          echo ${{ inputs.version }}
          echo ${{ inputs.envname }}
