name: Deploy
on:
  workflow_call:
    inputs:
      envname:
        description: '部署环境'
        default: 'dev'
        type: string
      version:
        description: '部署版本'
        default: 'master'
        type: string
    secrets:
      SSH_HOST_DEV:
        required: true
      SSH_USERNAME_DEV:
        required: true
      SSH_KEY_DEV:
        required: true
      SSH_PORT_DEV:
        required: true
      SSH_HOST_PRD:
        required: true
      SSH_USERNAME_PRD:
        required: true
      SSH_KEY_PRD:
        required: true
      SSH_PORT_PRD:
        required: true
      GHCR_ACCESS_TOKEN:
        required: true
      DYUPS_TOKEN:
        required: true
      DYUPS_DB_HOST:
        required: true
      DYUPS_DB_PORT:
        required: true
      DYUPS_DB_DATABASE:
        required: true
      DYUPS_DB_USER:
        required: true
      DYUPS_DB_PASSWORD:
        required: true
      DYUPS_DB_CHARSET:
        required: true
      GHCR_MIRROR:
        required: true
  workflow_dispatch:
    inputs:
      envname:
        description: '部署环境'
        default: 'dev'
        type: choice
        options:
          - dev
          - prd
      version:
        description: '部署版本'
        default: 'master'
        type: string

env:
  REPO: xuexb/dyups
  IMAGE_VERSION: ${{ inputs.version || github.event.inputs.version }}
  ENV_NAME: ${{ inputs.envname || github.event.inputs.envname }}
  REPOSITORY_TAG: ghcr.io/xuexb/dyups:${{ inputs.version || github.event.inputs.version }}
  MIRROR_REPOSITORY_TAG: ${{ secrets.GHCR_MIRROR }}/xuexb/dyups:${{ inputs.version || github.event.inputs.version }}
  OWNER: xuexb
  CONTAINER_NAME: dyups

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.check_version.outputs.HTTP_CODE }}
    steps:
      - name: Generate Token
        id: generate_token
        run: |
          TOKEN=`curl -su ${{ env.OWNER }}:${{ secrets.GHCR_ACCESS_TOKEN }} https://ghcr.io/token\?scope\="repository:${{ env.REPO }}:pull" | awk -F '"' '{print $4}'`
          echo "::set-output name=GHCR_PULL_TOKEN::$TOKEN"
      - name: Check version
        id: check_version
        if: ${{ steps.generate_token.conclusion == 'success' }}
        run: |
          HTTP_CODE=`curl -sL -w '%{http_code}' --connect-timeout 5 -H 'Authorization: Bearer ${{ steps.generate_token.outputs.GHCR_PULL_TOKEN }}' https://ghcr.io/v2/${{ env.REPO }}/manifests/${{ env.IMAGE_VERSION }} -o /dev/null`
          if [ "$HTTP_CODE" == "200" ]; then
            echo "::set-output name=HTTP_CODE::$HTTP_CODE"
          else
            echo "curl https://ghcr.io/v2/${{ env.REPO }}/manifests/${{ env.IMAGE_VERSION }} Response => $HTTP_CODE"
            exit 1
          fi
  set-env:
    runs-on: ubuntu-latest
    needs: check-version
    if: ${{ needs.check-version.outputs.result == '200' }}
    outputs:
      ssh_host: ${{ steps.set-ssh-env.outputs.ssh_host }}
      sshhost: ${{ steps.set-ssh-env.outputs.sshhost }}
      test: ${{ steps.set-ssh-env.outputs.test }}
      ssh_host2: ${{ steps.set_ssh_env.outputs.ssh_host }}
      sshhost2: ${{ steps.set_ssh_env.outputs.sshhost }}
      test2: ${{ steps.set_ssh_env.outputs.test }}
    steps:
      - name: set-ssh-env
        id: set_ssh_env
        run: |
          if [ "${{ env.ENV_NAME }}" == "dev" ]; then
            echo "ssh_host dev = ${{ secrets.SSH_HOST_DEV }}"
            echo "::set-output name=ssh_host::${{ secrets.SSH_HOST_DEV }}"
            echo "::set-output name=sshhost::${{ secrets.SSH_HOST_DEV }}"
            echo "::set-output name=test::okkkk"
            echo "::set-output name=ssh_host2::${{ secrets.SSH_HOST_DEV }}"
            echo "::set-output name=sshhost2::${{ secrets.SSH_HOST_DEV }}"
            echo "::set-output name=test2::okkkk"
          else
            echo "ssh_host prd = ${{ secrets.SSH_HOST_PRD }}"
            echo "::set-output name=ssh_host::${{ secrets.SSH_HOST_PRD }}"
          fi
  deploy:
    runs-on: ubuntu-latest
    needs: [set-env, check-version]
    if: |
      needs.check-version.outputs.result == '200'
      && (inputs.envname == 'dev' || github.event.inputs.envname == 'dev')
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_DEV }}
          username: ${{ secrets.SSH_USERNAME_DEV }}
          key: ${{ secrets.SSH_KEY_DEV }}
          port: ${{ secrets.SSH_PORT_DEV }}
          debug: true
          command_timeout: 30m
          script: |
            docker pull ${{ env.MIRROR_REPOSITORY_TAG }} \
              && docker ps -aq --filter "name=${{ env.CONTAINER_NAME }}" | xargs docker rm -f || echo "Delete fail" \
              && docker run \
                -p 80:80 \
                -p 443:443 \
                --rm \
                -d \
                --name "${{ env.CONTAINER_NAME }}" \
                --env "DYUPS_TOKEN=${{ secrets.DYUPS_TOKEN }}" \
                --env "DYUPS_DB_HOST=${{ secrets.DYUPS_DB_HOST }}" \
                --env "DYUPS_DB_PORT=${{ secrets.DYUPS_DB_PORT }}" \
                --env "DYUPS_DB_DATABASE=${{ secrets.DYUPS_DB_DATABASE }}" \
                --env "DYUPS_DB_USER=${{ secrets.DYUPS_DB_USER }}" \
                --env "DYUPS_DB_PASSWORD=${{ secrets.DYUPS_DB_PASSWORD }}" \
                --env "DYUPS_DB_CHARSET=${{ secrets.DYUPS_DB_CHARSET }}" \
                ${{ env.MIRROR_REPOSITORY_TAG }}
  test:
    runs-on: ubuntu-latest
    needs: [deploy, set-env]
    if: ${{ needs.deploy.result == 'success' }}
    steps:
      - name: dump env
        run: |
          echo "ssh_host = ${{ needs.set-env.outputs.ssh_host }}"
          echo "sshhost = ${{ needs.set-env.outputs.sshhost }}"
          echo "test = ${{ needs.set-env.outputs.test }}"
          echo "ssh_host2 = ${{ needs.set-env.outputs.ssh_host2 }}"
          echo "sshhost2 = ${{ needs.set-env.outputs.sshhost2 }}"
          echo "test2 = ${{ needs.set-env.outputs.test2 }}"
      - name: Test
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_DEV }}
          username: ${{ secrets.SSH_USERNAME_DEV }}
          key: ${{ secrets.SSH_KEY_DEV }}
          port: ${{ secrets.SSH_PORT_DEV }}
          debug: true
          command_timeout: 30m
          script: |
            if [ "$(curl -sL -w '%{http_code}' -H 'host: dyups' -H 'x-dyups-token: ${{ secrets.DYUPS_TOKEN }}' --connect-timeout 3 127.0.0.1/api/reload?r=$RANDOM -o /dev/null)" != "200" ]; then
              exit 1
            fi
