name: Publish

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
    branches:
      - master

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.meta.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_READ_WRITE_USERNAME }}
          password: ${{ secrets.GHCR_READ_WRITE_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: ghcr.io/${{ env.IMAGE_NAME }}
          flavor: |
            latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  depoly-gz:
    environment: gz
    needs: build-and-push-image
    if: ${{ needs.build-and-push-image.result == 'success' }}
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      version: ${{ needs.build-and-push-image.outputs.version }}
  depoly-sg:
    environment: sg
    needs: [depoly-gz, build-and-push-image]
    if: ${{ needs.depoly-gz.result == 'success' }}
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      version: ${{ needs.build-and-push-image.outputs.version }}
  depoly-bj:
    environment: bj
    needs: [depoly-sg, build-and-push-image]
    if: ${{ needs.depoly-sg.result == 'success' }}
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      version: ${{ needs.build-and-push-image.outputs.version }}
