name: Test cron

on:
  schedule:
    - cron: '26 12 * * *'

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
            echo "OK"
            echo ${{ github.event.schedule }}
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.WORKFLOW_TOKEN }}
          script: |
            try {
              const result = github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: "publish.yml",
                ref: "master",
              });
              console.log(result);
            } catch(error) {
              console.error(error);
              core.setFailed(error);
            }
